### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/SplashScreen$OnExitAnimationListener after upgrading from 5.0.4 to 5.1.0 

### ISSUE THREAD

**Issue by claudiozam** [zoontek/react-native-bootsplash#506]
### Bug summary

After upgrading the library from 5.04. to 5.1.0 the app stop working. I'm unable to run it, no splash screen at all.
 
It only happens in old android versions for example android 8 or 9.

Tested on android emulator Pixel_2_ API Level 28 and Samsung Galaxy S9 (real device)

`11-09 15:46:40.197 12563 12563 I MainActivity: MainActivity onCreate
11-09 15:46:40.198  3910  3910 I CarrierServices: [2] aww.a: Unbinding RcsMigrationService
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil: Rejecting re-init on previously-failed class java.lang.Class<com.zoontek.rnbootsplash.RNBootSplashModuleImpl$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/SplashScreen$OnExitAnimationListener;
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.zoontek.rnbootsplash.RNBootSplashModuleImpl.init(android.app.Activity, int) (RNBootSplashModuleImpl.java:48)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.zoontek.rnbootsplash.RNBootSplash.init(android.app.Activity, int) (RNBootSplash.java:11)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void co.xxxxxxx.mobile.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:22)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7136)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7127)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1271)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2893)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3048)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.os.Looper.loop() (Looper.java:193)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.window.SplashScreen$OnExitAnimationListener" on path: DexPathList[[zip file "/data/app/co.xxxxxxx.mobile-Utez88UH8fNlS7p2wU2aFQ==/base.apk"],nativeLibraryDirectories=[/data/app/co.xxxxxxx.mobile-Utez88UH8fNlS7p2wU2aFQ==/lib/arm64, /data/app/co.xxxxxxx.mobile-Utez88UH8fNlS7p2wU2aFQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.zoontek.rnbootsplash.RNBootSplashModuleImpl.init(android.app.Activity, int) (RNBootSplashModuleImpl.java:48)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.zoontek.rnbootsplash.RNBootSplash.init(android.app.Activity, int) (RNBootSplash.java:11)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void co.xxxxxxx.mobile.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:22)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7136)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7127)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1271)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2893)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3048)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.os.Looper.loop() (Looper.java:193)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil: 
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil: Rejecting re-init on previously-failed class java.lang.Class<com.zoontek.rnbootsplash.RNBootSplashModuleImpl$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/SplashScreen$OnExitAnimationListener;
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.zoontek.rnbootsplash.RNBootSplashModuleImpl.init(android.app.Activity, int) (RNBootSplashModuleImpl.java:48)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.zoontek.rnbootsplash.RNBootSplash.init(android.app.Activity, int) (RNBootSplash.java:11)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void co.xxxxxxx.mobile.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:22)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7136)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7127)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1271)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2893)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3048)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.os.Looper.loop() (Looper.java:193)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.window.SplashScreen$OnExitAnimationListener" on path: DexPathList[[zip file "/data/app/co.xxxxxxx.mobile-Utez88UH8fNlS7p2wU2aFQ==/base.apk"],nativeLibraryDirectories=[/data/app/co.xxxxxxx.mobile-Utez88UH8fNlS7p2wU2aFQ==/lib/arm64, /data/app/co.xxxxxxx.mobile-Utez88UH8fNlS7p2wU2aFQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.zoontek.rnbootsplash.RNBootSplashModuleImpl.init(android.app.Activity, int) (RNBootSplashModuleImpl.java:48)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.zoontek.rnbootsplash.RNBootSplash.init(android.app.Activity, int) (RNBootSplash.java:11)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void co.xxxxxxx.mobile.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:22)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7136)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7127)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1271)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2893)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3048)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1808)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.os.Looper.loop() (Looper.java:193)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil:   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
11-09 15:46:40.198 12563 12563 I .xxxxxxx.mobil: 
`

### Library version

5.1.0

### Environment info

```shell
System:
  OS: macOS 14.1.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 21.95 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.1.0
    path: /var/folders/pv/51qh3b417f995x35c1dfpyd80000gn/T/yarn--1699555941957-0.9834527421153583/node
  Yarn:
    version: 1.22.19
    path: /var/folders/pv/51qh3b417f995x35c1dfpyd80000gn/T/yarn--1699555941957-0.9834527421153583/yarn
  npm:
    version: 10.2.0
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/claudiozamoszczyk/.rvm/rubies/ruby-3.1.4/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 3.1.4
    path: /Users/claudiozamoszczyk/.rvm/rubies/ruby-3.1.4/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: ^0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false


**package.json**

{
  "name": "XXXXXXXMobileApp",
  "version": "3.12.18",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios --simulator='iPhone 15'",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "patch-package",
    "postversion": "react-native-version --never-amend --generate-build && node handing-post-version.js"
  },
  "dependencies": {
    "@alessiocancian/react-native-actionsheet": "^3.1.2",
    "@codler/react-native-keyboard-aware-scroll-view": "2.0.1",
    "@fortawesome/fontawesome-common-types": "file:./local_fortawesome/fontawesome-common-types",
    "@fortawesome/fontawesome-svg-core": "file:./local_fortawesome/fontawesome-svg-core",
    "@fortawesome/free-brands-svg-icons": "file:./local_fortawesome/free-brands-svg-icons",
    "@fortawesome/pro-light-svg-icons": "file:./local_fortawesome/pro-light-svg-icons",
    "@fortawesome/pro-regular-svg-icons": "file:./local_fortawesome/pro-regular-svg-icons",
    "@fortawesome/pro-solid-svg-icons": "file:./local_fortawesome/pro-solid-svg-icons",
    "@fortawesome/react-native-fontawesome": "file:./local_fortawesome/react-native-fontawesome",
    "@invertase/react-native-apple-authentication": "^2.2.0",
    "@notifee/react-native": "^7.7.1",
    "@react-native-async-storage/async-storage": "^1.17.6",
    "@react-native-clipboard/clipboard": "^1.10.0",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/datetimepicker": "^7.0.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/slider": "^4.4.2",
    "@react-native-firebase/analytics": "^18.0.0",
    "@react-native-firebase/app": "^18.0.0",
    "@react-native-firebase/messaging": "^18.0.0",
    "@react-native-google-signin/google-signin": "^10.0.1",
    "@react-native-picker/picker": "^2.4.0",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/elements": "^1.3.3",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@rneui/base": "^4.0.0-rc.8",
    "@rneui/themed": "^4.0.0-rc.8",
    "@types/uuid": "^8.3.4",
    "axios": "^0.24.0",
    "chance": "^1.1.9",
    "color": "^4.2.3",
    "detox": "^20.0.3",
    "ffmpeg-kit-react-native": "^6.0.1",
    "formik": "^2.2.6",
    "fsevents": "^2.3.3",
    "fuse.js": "^6.6.2",
    "i18n-js": "^4.3.0",
    "immutability-helper": "^3.1.1",
    "ios-deploy": "^1.12.2",
    "link-preview-js": "^2.1.15",
    "lodash": "^4.17.20",
    "md5": "^2.3.0",
    "moment-timezone": "^0.5.40",
    "patch-package": "^7.0.2",
    "postinstall-postinstall": "^2.1.0",
    "pretty-bytes": "^6.0.0",
    "randomcolor": "^0.6.2",
    "react": "18.2.0",
    "react-native": "^0.72.4",
    "react-native-add-calendar-event": "^4.2.2",
    "react-native-audio-recorder-player": "^3.5.1",
    "react-native-autolink": "^4.0.0",
    "react-native-base64": "^0.2.1",
    "react-native-blob-util": "^0.19.1",
    "react-native-bootsplash": "^5.1.0",
    "react-native-calendars": "1.1279.0",
    "react-native-color-palette": "^2.2.0",
    "react-native-config": "^1.5.0",
    "react-native-device-info": "^10.11.0",
    "react-native-document-picker": "^9.0.1",
    "react-native-easy-grid": "^0.2.2",
    "react-native-fast-image": "^8.5.4",
    "react-native-file-viewer": "^2.1.5",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-gifted-chat": "0.16.3",
    "react-native-hide-with-keyboard": "^1.2.1",
    "react-native-image-crop-picker": "^0.40.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-inappbrowser-reborn": "^3.5.1",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-loading-spinner-overlay": "^3.0.1",
    "react-native-localize": "^3.0.2",
    "react-native-masked-text": "^1.13.0",
    "react-native-mime-types": "^2.3.0",
    "react-native-modal": "^13.0.0",
    "react-native-modal-datetime-picker": "^17.0.0",
    "react-native-modal-selector": "^2.1.0",
    "react-native-orientation-locker": "^1.5.0",
    "react-native-permissions": "^4.0.0-beta.1",
    "react-native-progress": "^5.0.0",
    "react-native-push-notification-popup": "^1.6.0",
    "react-native-rate": "^1.2.4",
    "react-native-reanimated": "^3.5.2",
    "react-native-render-html": "^6.3.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.23.0",
    "react-native-share": "^9.1.0",
    "react-native-simple-default-props": "^1.0.0",
    "react-native-simple-toast": "^3.0.0",
    "react-native-spinkit": "^1.5.1",
    "react-native-svg": "^13.10.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-swiper": "^1.6.0",
    "react-native-system-navigation-bar": "^2.6.0",
    "react-native-toast-message": "^2.1.6",
    "react-native-vector-icons": "^10.0.0",
    "react-native-version": "^4.0.0",
    "react-native-video": "^5.2.1",
    "react-native-webview": "^13.2.2",
    "react-redux": "^8.0.2",
    "read-package-json": "^7.0.0",
    "redux": "^4.2.0",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1",
    "rn-placeholder": "^3.0.3",
    "rollbar-react-native": "^0.9.1",
    "sanitize-filename": "^1.6.3",
    "striptags": "^3.1.1",
    "url": "^0.11.2",
    "yup": "^0.32.8"
  },
  "devDependencies": {
    "@babel/core": "^7.19.6",
    "@babel/helper-string-parser": "^7.19.4",
    "@babel/plugin-proposal-class-properties": "^7.17.12",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.17.12",
    "@babel/plugin-proposal-optional-chaining": "^7.17.12",
    "@babel/plugin-transform-arrow-functions": "^7.17.12",
    "@babel/plugin-transform-shorthand-properties": "^7.16.0",
    "@babel/plugin-transform-template-literals": "^7.18.2",
    "@babel/preset-env": "^7.14.0",
    "@babel/preset-typescript": "^7.17.12",
    "@babel/runtime": "^7.20.1",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "babel-jest": "^29.2.2",
    "eslint": "^8.19.0",
    "jest": "^29.2.2",
    "metro-react-native-babel-preset": "0.77.0",
    "prettier": "^2.4.1",
    "properties-reader": "^2.3.0",
    "react-native-clean-project": "^4.0.1",
    "react-test-renderer": "18.2.0",
    "redux-devtools": "3.7.0"
  },
  "engines": {
    "node": ">=16"
  },
  "detox": {
    "test-runner": "jest",
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/XXXXXXX.app",
        "build": "xcodebuild -workspace ios/XXXXXXMobileApp.xcworkspace -scheme XXXXXXXMobileApp -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "device": {
          "type": "iPhone 11"
        }
      }
    }
  }
}
```

### Steps to reproduce

1. Click the app icon
2. Wait for the splash screen
3. No splash screen
4. The app stop working

### Reproducible sample code

```js
package co.xxxxxxx.mobile;

import android.os.Bundle;
import android.content.Intent;
import com.facebook.react.ReactActivity;

import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import android.util.Log;
import com.zoontek.rnbootsplash.RNBootSplash;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactActivityDelegate;

public class MainActivity extends ReactActivity {

  private static final String TAG = "MainActivity";

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    Log.i(TAG, "MainActivity onCreate");
    RNBootSplash.init(this, R.style.BootTheme);
    super.onCreate(null);
  }

  @Override
  protected String getMainComponentName() {
    return "XXXXXMobileApp";
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new DefaultReactActivityDelegate(
        this,
        getMainComponentName(),
        // If you opted-in for the New Architecture, we enable the Fabric Renderer.
        DefaultNewArchitectureEntryPoint.getFabricEnabled());
  }
}
```

**Comment by AdnanAshraf-gol** [comment]
Facing the same issue on android 7 , 8 . Its working with android 13

**Comment by zoontek** [comment]
The error here makes no sense, this part of the code didn't change and is still wrapped with the same `Build` condition (this is not used on Android < 12):

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
  // This is not called on Android 12 when activity is started using intent
  // (Android studio / CLI / notification / widget…)
  SplashScreen.OnExitAnimationListener listener = new SplashScreen.OnExitAnimationListener() {
    @Override
    public void onSplashScreenExit(@NonNull SplashScreenView view) {
      view.remove(); // Remove it immediately, without animation

      activity
        .getSplashScreen()
        .clearOnExitAnimationListener();
    }
  };

  activity
    .getSplashScreen()
    .setOnExitAnimationListener(listener);
}
```

**Comment by zoontek** [comment]
I tried to reproduce, but got another error in similar conditions. Fixed it: https://github.com/zoontek/react-native-bootsplash/releases/tag/5.1.1

Could you try it?

**Comment by AdnanAshraf-gol** [comment]
with 5.1.1 it working for me on both android 7 and android 8

**Comment by claudiozam** [comment]
Thanks @zoontek
